# -----------------------------
# Deployment for regapp
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-deployment
  labels:
    app: regapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
        - name: regapp
          image: 837960492697.dkr.ecr.us-east-1.amazonaws.com/demo:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---

# -----------------------------
# LoadBalancer Service
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: regapp
spec:
  selector:
    app: regapp
  ports:
    - port: 80          # 💡 Make this 80 to expose outside users easily
      targetPort: 8080  # 🔁 Container port inside the pod
  type: LoadBalancer
